name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # use your actual region

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name yele-eks-cluster

      - name: Set Image in Deployment YAML
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest|" deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml